name       : slirp4netns
version    : 0.4.3
release    : 4
source     :
    - https://github.com/rootless-containers/slirp4netns/archive/v0.4.3.tar.gz : d699bc28a031512ed4fe13ca5a812dbc00415a61d7444a41bac2da6b62f9c53a 
license    : GPL-2.0-or-later
component  : virt
summary    : User-mode networking for unprivileged network namespaces
description: |
    slirp4netns allows connecting a network namespace to the Internet in a completely unprivileged way, by connecting a TAP device in a network namespace to the usermode TCP/IP stack ("slirp").
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
