name       : slirp4netns
version    : 0.3.2
release    : 1
source     :
    - https://github.com/rootless-containers/slirp4netns/archive/v0.3.2.tar.gz : fe400337e857cee668a0c9161e2997af9c5c8cbaf4cbec12b32b458064eec380
license    : GPL-2.0-or-later
component  : virt
summary    : User-mode networking for unprivileged network namespaces
description: |
    slirp4netns allows connecting a network namespace to the Internet in a completely unprivileged way, by connecting a TAP device in a network namespace to the usermode TCP/IP stack ("slirp").
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
